chore: Downgrade execa to 8.x to resolve a CI failure
```
file:///usr/src/proposals/34:upgrade-10/node_modules/@agoric/synthetic-chain/node_modules/execa/lib/utils/max-listeners.js:1
import {addAbortListener} from 'node:events';
        ^^^^^^^^^^^^^^^^
SyntaxError: The requested module 'node:events' does not provide an export named 'addAbortListener'
```